server:
  port: 8090

spring:
  application-name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: gusers-service
          uri: lb://gusers-service
          predicates:
            - Path=/gymbook/user/**
          filters:
           - AuthenticationFilter            
            
        - id: gplans-service
          uri: lb://gplans-service
          predicates:
            - Path=/gymbook/plans/**
          filters:
           - AuthenticationFilter        
 
eureka:
   instance:
     hostname: localhost
   client:
     register-with-eureka: 'true'
     service-url:
       defaultZone: http://host.docker.internal:8761/eureka/
     fetch-registry: 'true'