server:
  port: 8088

spring:
  profiles:
    active: native	
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    fetch-registry: 'true'