server:
  port: 9092
spring:
     datasource:
        password: ${POSTGRESDBPASSWORD}
        username: ${POSTGRESDBUSER}
        url: ${POSTGRESDBURL}
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       
eureka:
   instance:
     hostname: localhost
   client:
     register-with-eureka: 'true'
     service-url:
       defaultZone: http://host.docker.internal:8761/eureka/
     fetch-registry: 'true'

