server:
   port: 9900
   api:
     username: king02102
     password: aa
      
spring:
     datasource:
       url: jdbc:postgresql://localhost:5432/gymbook
       username: postgres
       password: postgres
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



